### ISSUE TITLE
Game of Life example doesn't work

### ISSUE THREAD

**Issue by SpyrosRoum** [hecrj/iced#449]
Hello, I tried to copy everything for the Game Of Life but when I try to build it it fails. This is the output from doing `cargo check`:
The code in main.rs and style.rs is exactly copy-pasted

```
error[E0432]: unresolved import `iced::time`
  --> src/main.rs:10:5
   |
10 |     time, Align, Application, Checkbox, Column, Command, Container, Element,
   |     ^^^^ no `time` in the root

error[E0432]: unresolved imports `iced::canvas::Cache`, `iced::canvas::Cursor`, `iced::canvas::Event`, `iced::canvas::Geometry`, `iced::mouse`, `iced::Rectangle`
   --> src/main.rs:133:19
    |
133 |             self, Cache, Canvas, Cursor, Event, Frame, Geometry, Path, Text,
    |                   ^^^^^          ^^^^^^  ^^^^^         ^^^^^^^^ no `Geometry` in `canvas`
    |                   |              |       |
    |                   |              |       no `Event` in `canvas`
    |                   |              no `Cursor` in `canvas`
    |                   no `Cache` in `canvas`
134 |         },
135 |         mouse, Color, Element, HorizontalAlignment, Length, Point, Rectangle,
    |         ^^^^^ no `mouse` in the root                               ^^^^^^^^^ no `Rectangle` in the root

error[E0405]: cannot find trait `Program` in module `canvas`
   --> src/main.rs:288:22
    |
288 |     impl<'a> canvas::Program<Message> for Grid {
    |                      ^^^^^^^ not found in `canvas`

error: aborting due to 3 previous errors
```

**Comment by Songtronix** [comment]
which version of Iced do you use? Looks like the one from crates.io. However all examples refer to master. Checkout the [0.1](https://github.com/hecrj/iced/tree/0.1) branch to get examples which work with 0.1.1.

**Comment by SpyrosRoum** [comment]
Ah you are right, I didn't think about that at all. It looks like there is no game_of_life example in 0.1 branch so I guess it makes sense it doesn't work.
Since I am basically making Langton's Ant and I want to have the same controls as this I think I'll try to use the master branch, thanks!
