### ISSUE TITLE
Update to lyon 0.17 seems to have broken examples

### ISSUE THREAD

**Issue by kaimast** [hecrj/iced#1039]
Hi,

I get the following error on most recent master. 

```
error[E0599]: no method named `x_range` found for reference `&Box2D<S, UnknownUnit>` in the current scope
   --> /home/kai/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_geom-0.17.5/src/line.rs:438:29
    |
438 |         self.clipped_x(clip.x_range())?.clipped_y(clip.y_range())
    |                             ^^^^^^^ method not found in `&Box2D<S, UnknownUnit>`

error[E0599]: no method named `y_range` found for reference `&Box2D<S, UnknownUnit>` in the current scope
   --> /home/kai/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_geom-0.17.5/src/line.rs:438:56
    |
438 |         self.clipped_x(clip.x_range())?.clipped_y(clip.y_range())
    |                                                        ^^^^^^^ method not found in `&Box2D<S, UnknownUnit>`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `lyon_geom` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
```

After doing a `git bisect`, the compile error seems to be caused by the following commit: [d0fe7b57ea343665905933cdf206d8206be462b9] Update `lyon` to `0.17` in `iced_graphics`

**Comment by kaimast** [comment]
Okay. `rm Cargo.lock && cargo clean` fixed it.
